repos:
  # Basic file cleanup
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict

  # Markdown linting and formatting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ["--fix", "--config", ".markdownlint.json"]
        files: \.(md|markdown)$

  # Local link checking
  - repo: local
    hooks:
      - id: check-links
        name: Check documentation links
        entry: ./check-links.sh
        language: script
        files: docs/.*\.md$
        pass_filenames: false

  # Local build test
  - repo: local
    hooks:
      - id: test-build
        name: Test MkDocs build
        entry: poetry run mkdocs build --strict
        language: system
        files: (docs/.*\.md$|mkdocs\.yml$|pyproject\.toml$)
        pass_filenames: false
