version: "3"

vars:
  PYTHON_VERSION: 3.11
  SITE_NAME: beetween

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  install:
    desc: Install dependencies using Poetry
    cmds:
      - poetry install

  serve:
    desc: Start the MkDocs development server
    cmds:
      - poetry run mkdocs serve

  serve-all:
    desc: Start the MkDocs development server accessible from all interfaces
    cmds:
      - poetry run mkdocs serve --dev-addr=0.0.0.0:8000

  build:
    desc: Build the documentation site
    cmds:
      - poetry run mkdocs build

  deploy:
    desc: Deploy to GitHub Pages
    cmds:
      - poetry run mkdocs gh-deploy

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf site/
      - rm -rf .cache/

  lint:
    desc: Run linting tools
    cmds:
      - poetry run black docs/
      - poetry run isort docs/
      - poetry run flake8 docs/

  setup:
    desc: Initial setup - install dependencies and setup pre-commit
    cmds:
      - poetry install
      - poetry run pre-commit install
      - echo "Setup complete! Run 'task serve' to start development server"

  update:
    desc: Update dependencies
    cmds:
      - poetry update
      - poetry run pre-commit autoupdate

  list-features:
    desc: List all available features
    cmds:
      - echo "📋 Available Features:"
      - |
        if [ -d "docs/features" ]; then
          for feature_dir in docs/features/*/; do
            if [ -d "$feature_dir" ]; then
              feature_name=$(basename "$feature_dir")
              echo "   📁 $feature_name"
            fi
          done
        else
          echo "   No features directory found"
        fi
